### ISSUE TITLE
Lost connection to APM server?

### ISSUE THREAD

**Issue by slayer** [elastic/apm-agent-ruby#432]
Hi noticed that there are no new data from agent coming but rails is running and serving traffic

![image](https://user-images.githubusercontent.com/57521/58565964-62dde700-8238-11e9-9951-9aa811847ca6.png)

**Comment by mikker** [comment]
Hi there! Do the logs say anything about what might be going on?

**Comment by slayer** [comment]
I have found messages like
```

2019-05-29 00:50:40.696 | 2019-05-28T21:50:37.877Z 1 TID-osbomroz1 ERROR: [ElasticAPM] APM Server responded with an error:
```

and surroundings (I suppose related to this error):
![image](https://user-images.githubusercontent.com/57521/58571610-c9680280-8242-11e9-9e3d-091103996c04.png)

**Comment by mikker** [comment]
This sounds like a problem I've just solved in #431. One sec, I'll make a release and you can upgrade and see if that fixes it?

**Comment by slayer** [comment]
Sure

**Comment by mikker** [comment]
2.8.1 is out and includes a fix for large queries. Let me know if it solves your issue.

**Comment by slayer** [comment]
Looks like it helped a lot, but some holes still exist. Will try investigate.
![image](https://user-images.githubusercontent.com/57521/59022288-26bd0e80-8856-11e9-8570-8ed1c05597cb.png)

**Comment by mikker** [comment]
Perhaps try limiting the amount of data with the options `stack_trace_limit` (suggest `50`) and `transaction_sample_rate` (suggest `0.5` to start with).

**Comment by mikker** [comment]
Closing this to tidy up. Feel free to reopen if you still think this is an agent issue!

**Comment by slayer** [comment]
Sure, I believe issue fixed! Thanks.
